### PR TITLE
fix: #8 export paths resolved

### LINKED ISSUE #8: [BUG] Missing exports from adapters path
### [BUG] Missing exports from adapters path

> [!CAUTION]
> We have only exports from `@bdcode/sms` path but `@bdcode/sms/adapters/<adapter>` path for specific exports are not working as we planned.

We need to fix the sub-path exports to have adapter specific exports. Specially the types are really important to others tools sometimes.

### PR DESCRIPTION
**Pull request by mrmeaow**
## Related Issue
Closes #8 bug reported earlier

## What does this PR do?
- Fixes the export paths issues

## Types of changes:
- [x] Bug fix
- [x] Documentation update

## Checklist:
- [x] Followed code style guidelines
- [x] Updated documentation (if applicable)

### CODE REVIEW

File: lib/adapters/smsnetbd.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@
  * [SmsNetBd](https://sms.net.bd) SMS Gateway Adapter
  * This adapter is used to send SMS via SmsNetBd API.
  * -----------------------------------------------------------
- * Author: Mr. Meaow
+ * Author: @codecontinent/opensource team.
```
Comment (mahabubx7) [inline lib/adapters/smsnetbd.ts:6]: Cool 👍🏼

File: lib/adapters/smsnetbd.ts [hunk 2]
```diff
@@ -13,7 +13,7 @@
 import { z } from "zod";
 import { axApiCall, composeHeaders } from "../common.js";
 
-const SmsNetBdEndpoints = {
+export const SmsNetBdEndpoints = {
```
Comment (mahabubx7) [inline lib/adapters/smsnetbd.ts:16]: Loved this idea 🫶

File: package.json [hunk 3]
```diff
@@ -109,7 +108,9 @@
   },
   "tsup": {
     "entry": [
-      "lib/index.ts"
+      "lib/index.ts",
```
Comment (mahabubx7) [inline package.json:111]: Oops! we missed it earlier 😮

File: package.json [hunk 4]
```diff
@@ -109,7 +108,9 @@
...
+      "lib/mod.ts",
+      "lib/adapters/smsnetbd.ts"
```
Comment (mahabubx7) [inline package.json:113]: Oops! we just missed this earlier 🤯

**Review by mahabubx7 — APPROVED** [review]
### Approved ✅ 

Huh! Next time, we need to be more careful!
